### ISSUE TITLE
"Reset your votes" throws error

### ISSUE THREAD

**Issue by ZID-TU-Graz** [nextcloud/polls#2683]
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [X] I agree to follow Nextcloud's [Code of Conduct](https://nextcloud.com/contribute/code-of-conduct/).

### What went wrong, what did you observe?

"Reset your votes" is not possible, because it throws an error ("Error while resetting votes" / "Fehler beim Zurücksetzen der Stimmabgaben" in german)

![Bildschirmfoto_2022-11-28_09-04-33](https://user-images.githubusercontent.com/100593683/204225159-55d3f692-4711-4afb-82b3-4d373d91b05b.png)

We observe a 401 status code and the JSON response: message "denied permission edit"

### What did you expect, how polls should behave instead?

No error should be thrown, instead the votes should be resetted.

### What steps does it need to replay this bug?

1. Create a poll
2. Make a vote
3. Click the button "Reset your votes"


### Installation method

Installed/updated from the appstore (Apps section of your site)

### Installation type

Updated from a minor version within same major version (i.e. 4.0.0 to 4.1.1)

### Which browser did you use, when experiencing the bug?

- [X] Firefox
- [x] Chrome
- [ ] Chromium/Chromium based (i.e. Edge)
- [ ] Safari
- [ ] Other/Don't know

### Other browser

_No response_

### Which System did you use, when experiencing the bug?

- [X] Windows
- [X] Linux
- [x] MacOs
- [ ] iOS
- [ ] Android
- [ ] Other/Don't know

### Other OS

_No response_

### Add your browser log here

```
Error deleting votes 
Object { error: {…} }
​
error: Object { data: {…}, status: 401, statusText: "Unauthorized", … }
​
<prototype>: Object { … }
votes.js:159:3
    t votes.js:159
    d votes.js:2
    _invoke votes.js:2
    b votes.js:2
    f votes.js:2
    s votes.js:2
    (Async: promise callback)
    f votes.js:2
    o votes.js:2
    h votes.js:2
    h votes.js:2
    resetVotes votes.js:146
    A vuex.esm.js:851
    dispatch vuex.esm.js:516
    dispatch vuex.esm.js:406
    r UserMenu.vue:340
    l UserMenu.vue:97
    _invoke UserMenu.vue:97
    y UserMenu.vue:97
    L UserMenu.vue:97
    a UserMenu.vue:97
    E UserMenu.vue:97
    E UserMenu.vue:97
    resetVotes UserMenu.vue:338
    click UserMenu.vue:1
    VueJS 4
    onClick ncvuecomponents.js:2
    VueJS 33


{
  "error": {
    "data": {
      "message": "denied permission edit"
    },
    "status": 401,
    "statusText": "Unauthorized",
    "headers": {
      "cache-control": "no-cache, no-store, must-revalidate",
      "connection": "Keep-Alive",
      "content-length": "36",
      "content-security-policy": "default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'",
      "content-type": "application/json; charset=utf-8",
      "date": "Mon, 28 Nov 2022 11:34:19 GMT",
      "expires": "Thu, 19 Nov 1981 08:52:00 GMT",
      "feature-policy": "autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'",
      "keep-alive": "timeout=5, max=36",
      "pragma": "no-cache",
      "referrer-policy": "no-referrer",
      "server": "Apache/2.4.54 (Debian)",
      "strict-transport-security": "max-age=15552000; includeSubDomains",
      "x-content-type-options": "nosniff",
      "x-frame-options": "SAMEORIGIN",
      "x-permitted-cross-domain-policies": "none",
      "x-request-id": "****",
      "x-robots-tag": "none",
      "x-xss-protection": "1; mode=block"
    },
    "config": {
      "transitional": {
        "silentJSONParsing": true,
        "forcedJSONParsing": true,
        "clarifyTimeoutError": false
      },
      "transformRequest": [
        null
      ],
      "transformResponse": [
        null
      ],
      "timeout": 0,
      "xsrfCookieName": "XSRF-TOKEN",
      "xsrfHeaderName": "X-XSRF-TOKEN",
      "maxContentLength": -1,
      "maxBodyLength": -1,
      "env": {
        "FormData": null
      },
      "headers": {
        "Accept": "application/json",
        "requesttoken": "*****"
      },
      "method": "delete",
      "url": "/index.php/apps/polls/poll/1234/user"
    },
    "request": {}
  }
}
```

![Bildschirmfoto_2022-11-28_12-37-46](https://user-images.githubusercontent.com/100593683/204268872-bcf6e449-d972-4d12-9f94-d09a49aa2e34.png)


### Additional client environment information

_No response_

### NC version

Nextcloud 24 (Nextcloud Hub 2)

### Other Nextcloud version

_No response_

### PHP engine version

PHP 8.0

### Other PHP version

_No response_

### Database engine

MariaDB

### Database Engine version or other Database

_No response_

### Which user-backends are you using?

- [ ] Default user-backend _(database)_
- [X] LDAP/ Active Directory
- [ ] SSO - SAML
- [ ] Other/Don't know

### Add your nextcloud server log here

```shell
no relevant entry is logged
```


### Additional environment informations

_No response_

### Configuration report

_No response_

### List of activated Apps

```
                                                                                                                                                                                                                                                                                                                  
Enabled:                                                                                                                                                                                                                                                                                                                                                                                                   
  - accessibility: 1.10.0                                                                                                                                                                                                                                                                                                                                                                                  
  - activity: 2.16.0                                                                                                                                                                                                                                                                                                                                                                                       
  - admin_audit: 1.14.0                                                                                                                                                                                                                                                                                                                                                                                    
  - announcementcenter: 6.3.1                                                                                                                                                                                                                                                                                                                                                                              
  - apporder: 0.15.0                                                                                                                                                                                                                                                                                                                                                                                       
  - bbb: 2.3.1                                                                                                                                                                                                                                                                                                                                                                                             
  - bookmarks: 11.0.4                                                                                                                                                                                                                                                                                                                                                                                      
  - bruteforcesettings: 2.4.0                                                                                                                                                                                                                                                                                                                                                                              
  - calendar: 3.5.2                                                                                                                                                                                                                                                                                                                                                                                        
  - circles: 24.0.1                                                                                                                                                                                                                                                                                                                                                                                        
  - cloud_federation_api: 1.7.0                                                                                                                                                                                                                                                                                                                                                                            
  - comments: 1.14.0                                                                                                                                                                                                                                                                                                                                                                                       
  - contacts: 4.2.2                                                                                                                                                                                                                                                                                                                                                                                        
  - contactsinteraction: 1.5.0                                                                                                                                                                                                                                                                                                                                                                             
  - dashboard: 7.4.0                                                                                                                                                                                                                                                                                                                                                                                       
  - dav: 1.22.0                                                                                                                                                                                                                                                                                                                                                                                            
  - deck: 1.7.2                                                                                                                                                                                                                                                                                                                                                                                            
  - drawio: 1.0.3                                                                                                                                                                                                                                                                                                                                                                                          
  - federatedfilesharing: 1.14.0                                                                                                                                                                                                                                                                                                                                                                           
  - federation: 1.14.0                                                                                                                                                                                                                                                                                                                                                                                     
  - files: 1.19.0                                                                                                                                                                                                                                                                                                                                                                                          
  - files_antivirus: 3.3.1                                                                                                                                                                                                                                                                                                                                                                                 
  - files_external: 1.16.1                                                                                                                                                                                                                                                                                                                                                                                 
  - files_lock: 24.0.1                                                                                                                                        
  - files_markdown: 2.3.6                                                                                                                                     
  - files_pdfviewer: 2.5.0                                                                                                                                    
  - files_rightclick: 1.3.0                                                                                                                                   
  - files_sharing: 1.16.2                                                                                                                                     
  - files_trashbin: 1.14.0                                                                                                                                                                                                        
  - files_versions: 1.17.0                                                                                                                                    
  - firstrunwizard: 2.13.0                                                                                                                                    
  - forms: 2.5.1                                        
  - group_default_quota: 0.1.4                                                                                                                                                                       
  - groupfolders: 12.0.2                                                                          
  - impersonate: 1.11.0                                                                           
  - logreader: 2.9.0                                                                              
  - lookup_server_connector: 1.12.0                                                               
  - metadata: 0.17.0                                                                              
  - nextcloud_announcements: 1.13.0                                                               
  - notes: 4.5.1                                                                                                                                                                                     
  - notifications: 2.12.1                                        
  - oauth2: 1.12.0                                               
  - oidc_login: 2.3.3                                            
  - onlyoffice: 7.5.8                                            
  - password_policy: 1.14.0                                      
  - photos: 1.6.0                                                
  - polls: 3.8.3                                                 
  - previewgenerator: 5.1.1                                      
  - privacy: 1.8.0                                               
  - provisioning_api: 1.14.0                                                   
  - qownnotesapi: 22.10.0                                                      
  - recommendations: 1.3.0                                                     
  - serverinfo: 1.14.0                                                         
  - settings: 1.6.0                                                            
  - sharebymail: 1.14.0                                                        
  - survey_client: 1.12.0                                                      
  - systemtags: 1.14.0                                                         
  - tasks: 0.14.5                                                              
  - text: 3.5.1                                                                
  - theming: 1.15.0                                                            
  - twofactor_backupcodes: 1.13.0                                              
  - updatenotification: 1.14.0                                                 
  - user_ldap: 1.14.1                                                          
  - user_status: 1.4.0                                                         
  - viewer: 1.8.0                                                              
  - weather_status: 1.4.0                                                      
  - webapppassword: 22.10.0                                                    
  - workflowengine: 2.6.0                                                      
Disabled:                                                                                         
  - encryption                                                                                    
  - files_texteditor: 2.14.0                                                                      
  - files_videoplayer: 1.13.0                                                                     
  - jsloader: 1.5.0                                                                               
  - support: 1.1.1                                                                                
  - theming_customcss: 1.12.0                                                   
```

### Nextcloud Signing status

_No response_

### Additional Information

_No response_
